name: eve

packages:
  - packages/**

scripts:

  # Setup flutter_plugin_tools and tuneup
  setup:
    run: |
      pub global activate tuneup
      dart pub global activate flutter_plugin_tools
      
  # Execute the analyzer, formatter and test
  lint:all:
    run: melos run analyze:tuneup && melos run format:all && melos run test
    description: Run all static analysis checks

  # Analyze the project for Dart analysis issues.
  analyze:
    run: |
      melos exec -c 5 -- dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.

  # Analyze the project for Dart analysis issues.
  #  - Requires `pub global activate tuneup`.
  analyze:tuneup:
    run: |
      melos exec -c 5 -- tuneup check
    description: |
      Run tuneup check in all packages.

  # Formats the code of all packages (Java, Objective-C, and Dart).
  #  - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
  #  - Requires `git`.
  #  - Requires `clang-format` (can be installed via Brew on MacOS).
  format:all: pub global run flutter_plugin_tools format

  # Formats all the Dart files being commited.
  format:commit:
    run: |
      files=`git diff --name-only --cached | grep .dart | xargs`
      if [ ! -z "$files" ]
      then
          flutter format $files
          git add $files
          exit 0
      fi

  # Run standard flutter tests in all packages that have them.
  test: >
    melos exec -c 1 --fail-fast --dir-exists=test --ignore="*example*" --ignore="*web*" -- \
      flutter test

  # Clean things very deeply, can be used to establish "pristine checkout" status
  clean:deep: >
    git clean -x -d -f -q

  # Additional cleanup lifecycle script, executed when `melos clean` is ran.
  postclean: >
    melos exec -c 6 -- "flutter clean"

  # Run all targets generally expected in CI for a full local quality check
  qualitycheck: >
    melos run clean:deep && melos clean && melos bootstrap && melos run lint:all

dev_dependencies:
  flutter_lints: 1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
