name: abstractions
description: Contains all project abstractions
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  design_system:
    path: ../design_system
    
  i18n:
    path: ../i18n

  navigator:
    path: ../navigator

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
