name: eve
description: Eve core
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter   

  abstractions:
    path: ../abstractions

  dependencies:
    path: ../dependencies

  di:
    path: ../di

  i18n:
    path: ../i18n

  navigator:
    path: ../navigator

  reactive:
    path: ../reactive

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
